services:
  - type: web
    name: crm-podprovar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

